[rules.compress_ship]
match = "/var/log/nginx/rotated.%Y-%m-%d.log"
after = "2d"
run = ["zstd --rm $$", "aws s3 cp $$ s3://backup-bucket/$(basename $$)"]

[rules.gc]
match = "/var/log/nginx/rotated.%Y-%m-%d.log.zst"
after = "7d"
run = ["rm $$"]
